name: ChatGPT Code Review

on:
  pull_request:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Pull Request Branch
    - name: Checkout Pull Request Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    # Step 2: Fetch Master Branch
    - name: Fetch Master Branch
      run: git fetch origin master

    # Step 3: Get Pull Request Diff
    - name: Get Pull Request Diff
      run: |
        git diff origin/master...HEAD > pr_diff.txt
        if [ ! -s pr_diff.txt ]; then
          echo "No changes detected in the pull request. Exiting."
          exit 0
        fi
        cat pr_diff.txt

    # Step 4: Generate Review Suggestions
    - name: Generate Review Suggestions
      id: chatgpt_review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Preparing to send diff to GPT-4o-mini model."
        DIFF=$(cat pr_diff.txt | jq -Rsa .)
        RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4o-mini",
            "messages": [
              {"role": "system", "content": "You are a code reviewer. Analyze the following code diff and provide detailed feedback."},
              {"role": "user", "content": '"$DIFF"'}
            ]
          }')
        echo "Response from OpenAI API: $RESPONSE" >> debug.log
        echo "$RESPONSE" | jq '.' > review_suggestions.json || echo "Invalid JSON response." > review_suggestions.json
        cat review_suggestions.json

    # Step 5: Post Review Suggestions to PR
    - name: Post Review Comments
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ## ChatGPT Code Review Suggestions
          $(cat review_suggestions.json)

    # Step 6: Upload Debug Logs
    - name: Upload Debug Logs
      uses: actions/upload-artifact@v3
      with:
        name: debug-log
        path: debug.log
