name: ChatGPT Code Review

on:
  pull_request:
    branches:
      - master

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Pull Request Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Fetch Master Branch
      run: git fetch origin master

    - name: Get Pull Request Diff
      run: |
        git diff origin/master...HEAD > pr_diff.txt
        cat pr_diff.txt

    - name: Generate Review Suggestions
      id: chatgpt_review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        DIFF=$(cat pr_diff.txt | jq -Rsa .)
        RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "You are a code reviewer. Analyze the following code diff and provide feedback."},
              {"role": "user", "content": '"$DIFF"'}
            ]
          }')
        echo "$RESPONSE" > review_suggestions.json
        cat review_suggestions.json


    - name: Post Review Comments
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ## ChatGPT Code Review Suggestions
          $(cat review_suggestions.json)
