name: Create Issue from Project Card

on:
  project_card:
    types:
      - created # 프로젝트 카드가 생성될 때 트리거

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract Project Card Details
      id: extract
      run: |
        echo "CARD_ID=$(jq -r '.project_card.id' < "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV
        echo "CARD_CONTENT=$(jq -r '.project_card.note' < "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV

    - name: Create Issue from Card
      id: create_issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "New Task: ${{ env.CARD_CONTENT }}"
        content: "Automatically created from project card"
        labels: |
          project-card

    - name: Update Project Card with Issue Link
      run: |
        ISSUE_NUMBER=$(echo "${{ steps.create_issue.outputs.issue_number }}")
        ISSUE_URL="https://github.com/${{ github.repository }}/issues/${ISSUE_NUMBER}"
        curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/projects/columns/cards/${{ env.CARD_ID }} \
          -d "{\"note\":\"${{ env.CARD_CONTENT }} - [Issue #${ISSUE_NUMBER}](${ISSUE_URL})\"}"
