name: Docker Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Check out repository
      uses: actions/checkout@v3

    # 2. Docker 이미지 빌드
    - name: Build Docker image
      run: |
        docker build -t space-invaders .

    # 3. Docker 컨테이너 실행 및 테스트
    - name: Run and test container
      run: |
        docker run --rm space-invaders
