name: Link Issues with Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  link-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Link issues automatically
        uses: actions/github-script@v6
        with:
          script: |
            const issueKeys = context.payload.pull_request.body.match(/#\d+/g);
            if (issueKeys) {
              issueKeys.forEach(async (key) => {
                await github.issues.createComment({
                  ...context.repo,
                  issue_number: key.replace('#', ''),
                  body: `Linked to Pull Request: #${context.payload.pull_request.number}`
                });
              });
            }
