name: Generate and Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff --name-only origin/${{ github.base_ref }} > changed-files.txt
        cat changed-files.txt

    - name: Extract changed methods
      id: changed_methods
      run: |
        CHANGED_FILES=$(cat changed-files.txt | grep '\.java$')
        for FILE in $CHANGED_FILES; do
          echo "Processing $FILE"
          git diff origin/${{ github.base_ref }} -- $FILE | grep '^\+' | grep 'public ' >> changed-methods.txt || true
        done
        cat changed-methods.txt

    - name: Generate test code using ChatGPT API
      id: generate_tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        while IFS= read -r METHOD; do
          echo "Generating test for: $METHOD"
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "You are a Java developer. Generate JUnit 5 test code."},
                {"role": "user", "content": "Write a JUnit test for the following method:\n'"$METHOD"'"}
              ]
            }')
          echo "$RESPONSE" >> generated-tests.java
        done < changed-methods.txt

    - name: Run generated tests
      run: |
        echo "Running tests..."
        ./gradlew test
