name: Generate and Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff --name-only origin/${{ github.base_ref }} > changed-files.txt
        cat changed-files.txt

    - name: Extract changed methods
      id: changed_methods
      run: |
        CHANGED_FILES=$(cat changed-files.txt | grep '\.java$')
        for FILE in $CHANGED_FILES; do
          echo "Processing $FILE"
          git diff origin/${{ github.base_ref }} -- $FILE \
            | grep -E '^\+.*(public|protected|private|default).*\(.*\)\s*{' \
            | sed 's/^+//g' >> changed-methods.txt || true
        done
        cat changed-methods.txt
    
    - name: Generate test code using ChatGPT API
      id: generate_tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        while IFS= read -r METHOD; do
          echo "Generating test for: $METHOD"
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-4",
              "messages": [
                {"role": "system", "content": "You are a Java developer. Generate only valid JUnit 5 test code. Do not include any explanations or additional text."},
                {"role": "user", "content": "Write a JUnit test for the following method:\n'"$METHOD"'"}
              ]
            }')
          echo "Full response: $RESPONSE" >> debug-response.json
          TEST_CODE=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "Extracted test code: $TEST_CODE" >> debug-response.json
    
          # 유효성 검사
          if [ -z "$TEST_CODE" ] || [ "$TEST_CODE" == "null" ]; then
            echo "Error: Invalid test code for method: $METHOD" >> debug-response.json
          else
            echo "$TEST_CODE" >> app/src/test/java/org/example/AppTest.java
          fi
        done < changed-methods.txt


    - name: Run generated tests
      run: |
        echo "Running tests..."
        ./gradlew test
